#!/usr/bin/env bash
# dev-env macOS setup. Copies dotfiles/configs/scripts from the repo into $HOME.
# Deploy model: COPY (not symlink) — re-run after `git pull` to sync. Idempotent.
set -euo pipefail

# --- Darwin guard ---
if [ "$(uname -s)" != "Darwin" ]; then
    echo "This script is for macOS only. Use linux/omarchy/install.sh on the hub."
    exit 1
fi

echo "=== dev-env macOS Setup ==="

# --- Homebrew ---
if ! command -v brew >/dev/null 2>&1; then
    echo "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Load brew into this shell's environment (Apple Silicon vs Intel prefix).
if [ -x /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
elif [ -x /usr/local/bin/brew ]; then
    eval "$(/usr/local/bin/brew shellenv)"
else
    echo "Homebrew install appears to have failed: no brew binary found." >&2
    exit 1
fi

# --- Paths ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# --- Brew bundle ---
echo ""
echo "Installing packages from Brewfile..."
brew bundle --file="$SCRIPT_DIR/Brewfile"

# --- Directories ---
mkdir -p "$HOME/.config" "$HOME/.local/bin" "$HOME/.cache/theme"

# --- Copy dotfiles and configs ---
echo ""
echo "Copying config files..."

cp "$SCRIPT_DIR/.zshrc"           "$HOME/.zshrc";                    echo "  -> ~/.zshrc"
cp "$SCRIPT_DIR/.zprofile"        "$HOME/.zprofile";                 echo "  -> ~/.zprofile"
cp "$SCRIPT_DIR/.tmux.conf"       "$HOME/.tmux.conf";                echo "  -> ~/.tmux.conf"
ln -sf "$SCRIPT_DIR/.aerospace.toml" "$HOME/.aerospace.toml";          echo "  -> ~/.aerospace.toml (symlink)"
cp "$SCRIPT_DIR/starship.toml"    "$HOME/.config/starship.toml";     echo "  -> ~/.config/starship.toml"
mkdir -p "$HOME/Library/Application Support/Cursor/User"
cp "$SCRIPT_DIR/cursor/keybindings.json" "$HOME/Library/Application Support/Cursor/User/keybindings.json"; echo "  -> Cursor keybindings.json (KEYBINDINGS.md Ctrl set)"
# IDE settings: common/vscode/settings.json is the one file for BOTH Cursor and VS Code on both
# machines (ruling 2026-09-09). The Mac adds the Remote-SSH platform hint for the hub.
for _ide in Code Cursor; do
    _u="$HOME/Library/Application Support/$_ide/User"; mkdir -p "$_u"
    python3 - "$SCRIPT_DIR/../common/vscode/settings.json" "$_u/settings.json" <<'PYS'
import json, sys
d = json.load(open(sys.argv[1])); d["remote.SSH.remotePlatform"] = {"linux": "linux"}
json.dump(d, open(sys.argv[2], "w"), indent=2); open(sys.argv[2], "a").write("\n")
PYS
    echo "  -> $_ide settings.json (common/vscode + remote.SSH.remotePlatform)"
done
mkdir -p "$HOME/.hammerspoon"
# Symlinks, not copies (2026-08-27): ~/dev-env is a Syncthing folder, so a Linux
# edit reaches the live Mac config without re-running this script.
for lua in "$SCRIPT_DIR"/hammerspoon/*.lua; do ln -sf "$lua" "$HOME/.hammerspoon/$(basename "$lua")"; done; echo "  -> ~/.hammerspoon/ (symlinks)"

# --- Copy bin scripts (make executable) ---
echo ""
echo "Installing scripts to ~/.local/bin..."
for script in theme theme-extras menu-toggle new-window iterm2-window; do
    cp "$SCRIPT_DIR/bin/$script" "$HOME/.local/bin/$script"
    chmod +x "$HOME/.local/bin/$script"
    echo "  -> ~/.local/bin/$script"
done
cp "$SCRIPT_DIR/../common/bin/keybindings-menu" "$HOME/.local/bin/keybindings-menu"; chmod +x "$HOME/.local/bin/keybindings-menu"; echo "  -> ~/.local/bin/keybindings-menu (Cmd+K cheat sheet)"

# --- Tools with no theme file follow the terminal ANSI palette (= active theme);
#     glow reads the style theme-extras renders on every switch ---
mkdir -p "$HOME/.config/bat" "$HOME/.config/glow" "$HOME/.config/micro"
printf -- '--theme=ansi\n' > "$HOME/.config/bat/config";                          echo "  -> ~/.config/bat/config (ansi)"
printf 'style: "%s/.config/glow/rai.json"\npager: false\nwidth: 80\n' "$HOME" > "$HOME/.config/glow/glow.yml"; echo "  -> ~/.config/glow/glow.yml"
python3 - "$HOME/.config/micro/settings.json" <<'PYM'
import json, sys, os
p = sys.argv[1]; d = json.load(open(p)) if os.path.exists(p) else {}
d["colorscheme"] = "simple"; open(p, "w").write(json.dumps(d, indent=2) + "\n")
PYM
echo "  -> ~/.config/micro/settings.json (colorscheme simple)"

# --- Wallpaper helper: NSWorkspace setter (macOS Sonoma+/Tahoe no longer renders
#     wallpapers via the legacy System Events 'set picture'; the theme switcher calls this) ---
if command -v swiftc >/dev/null 2>&1; then
    swiftc -O -o "$HOME/.local/bin/set-wallpaper" "$SCRIPT_DIR/bin/set-wallpaper.swift" \
        && codesign -s - -f "$HOME/.local/bin/set-wallpaper" >/dev/null 2>&1 \
        && echo "  -> ~/.local/bin/set-wallpaper (compiled)"
else
    echo "  !! swiftc not found (install Xcode Command Line Tools) — wallpaper switching will no-op"
fi

# --- iTerm2 (terminal) ---
# The profile itself (colors, font, keys) is a Dynamic Profile generated by the
# theme switcher into ~/Library/Application Support/iTerm2/DynamicProfiles/ on
# every `theme` run — nothing to copy. App-level prefs are set here.
echo ""
echo "Applying iTerm2 preferences..."
defaults write com.googlecode.iterm2 Bidi -bool true                          # Arabic/RTL
defaults write com.googlecode.iterm2 QuitWhenAllWindowsClosed -bool false
defaults write com.googlecode.iterm2 PromptOnQuit -bool false
defaults write com.googlecode.iterm2 OnlyWhenMoreTabs -bool false
defaults write com.googlecode.iterm2 TerminalMargin -int 14                   # window padding
defaults write com.googlecode.iterm2 TerminalVMargin -int 14
defaults write com.googlecode.iterm2 HideScrollbar -bool true
defaults write com.googlecode.iterm2 HideTab -bool true
defaults write com.googlecode.iterm2 TabStyleWithAutomaticOption -int 5       # Minimal theme
defaults write com.googlecode.iterm2 "Default Bookmark Guid" -string "rai-theme"
defaults write com.googlecode.iterm2 NoSyncTipsDisabled -bool true

# --- Themes (shared data under common/) ---
echo ""
if [ ! -d "$HOME/.config/themes" ]; then
    echo "Installing theme system to ~/.config/themes..."
    cp -R "$REPO_ROOT/common/themes" "$HOME/.config/themes"
    echo "  -> ~/.config/themes"
else
    echo "Note: ~/.config/themes already exists — left untouched (manual sync model)."
    echo "      To refresh, sync it from $REPO_ROOT/common/themes yourself."
fi

# Default active theme: everforest (only if nothing is selected yet).
if [ ! -e "$HOME/.config/themes/current.lua" ]; then
    ln -sfn "$HOME/.config/themes/everforest/theme.lua" "$HOME/.config/themes/current.lua"
    echo "  -> ~/.config/themes/current.lua (everforest)"
fi

# Default everforest wallpaper: everforest-1 (sorted-first of the uniform set).
# Seed the switcher cache only if unset, so a fresh install lands here without
# clobbering a later 'theme wallpaper next/prev' choice.
ef_wp_cache="$HOME/.cache/theme/everforest.wallpaper"
ef_wp="$HOME/.config/themes/everforest/wallpapers/everforest-1.jpg"
if [ ! -f "$ef_wp_cache" ] && [ -f "$ef_wp" ]; then
    echo "$ef_wp" > "$ef_wp_cache"
    echo "  -> default wallpaper: everforest = everforest-1"
fi

# --- Secrets bootstrap ---
echo ""
if [ ! -f "$HOME/.zshrc.local" ]; then
    cp "$SCRIPT_DIR/.zshrc.local.example" "$HOME/.zshrc.local"
    echo "  -> ~/.zshrc.local (from example)"
    echo ""
    echo "  ************************************************************"
    echo "  *  ACTION REQUIRED: edit ~/.zshrc.local and fill in your   *"
    echo "  *  real secrets (e.g. OPENROUTER_API_KEY). It is NOT       *"
    echo "  *  tracked by git and the example value is a placeholder.  *"
    echo "  ************************************************************"
fi

# --- TPM (tmux plugin manager) ---
echo ""
if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
    echo "Installing TPM..."
    git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
fi

# --- Default shell ---
echo ""
if [ "$(basename "${SHELL:-}")" != "zsh" ]; then
    echo "Your login shell is not zsh. To switch, run:"
    echo "    chsh -s \"\$(command -v zsh)\""
fi

# --- Done ---
echo ""
echo "=== Done ==="
echo "1. Restart your terminal (or run: exec zsh)."
echo "2. Run 'theme reload' to apply the active theme."
echo "3. In tmux, press prefix + I to install tmux plugins."
